### ISSUE TITLE
Early brainstorming about extension for nutrition vocabs

### ISSUE THREAD

**Issue by twamarc** [twamarc/ScheMed#13]
Action point from the 2015-08-28 meeting

**Comment by twamarc** [comment]
cc/ @mgh128

**Comment by mgh128** [comment]
Sorry I couldn't join the call in August.  However, I have discussed with my GS1 colleague Eric Kauz and we should be able to share the current draft of the GS1 vocabulary (as a Turtle file) within the next few days.  I will also attach some examples of the markup in JSON-LD and screenshots of the web-based tool we've developed - in order to more easily show the range of properties we have already defined that are relevant for nutritional info, ingredients, diet, allergens, additives.  We are already in discussions with Dan Brickley (Google / schema.org) about how the GS1 web vocabulary could become an extension to schema.org to provide more detailed information about products.  I'll try to prepare these over the next couple of days and we would very much welcome your feedback on this.   mark.harrison@gs1.org

**Comment by twamarc** [comment]
@mgh128
Great! Happy to see progress there. 
I think we will have a nutrition vocab extension in line with GS1 work, so it will not be included into health extension-that's my view, but let's discuss this in coming meeting to collect the community view on this.
Keep us posted. 
Will you attend the next TCall on 25th?

**Comment by mgh128** [comment]
I'll definitely try to join the next TCall on 25th September.  I'm aiming to share the vocabulary and examples with you by the end of this week if possible - or early next, so hopefully you all have a chance to take a look before the next TCall.

**Comment by twamarc** [comment]
Great!

**Comment by twamarc** [comment]
To be coordinated with discussions around the https://github.com/schemaorg/schemaorg/issues/607

**Comment by twamarc** [comment]
Let's consolidate all discussions about this topic in the broader and older issue: https://github.com/schemaorg/schemaorg/issues/458.
So I closed this one
